"""empty message

Revision ID: 564ed372830f
Revises: c94816355fc4
Create Date: 2025-08-03 22:26:34.202033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564ed372830f'
down_revision: Union[str, Sequence[str], None] = 'c94816355fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('file_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'file_path')
    # ### end Alembic commands ###
