"""empty message

Revision ID: 88f44c4e664c
Revises: c39f84ff9c53
Create Date: 2024-12-24 00:29:25.892845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f44c4e664c'
down_revision: Union[str, None] = 'c39f84ff9c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('extended_title', sa.String(length=255), nullable=False))
    op.drop_column('sources', 'year')
    op.drop_column('sources', 'author')
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('second_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'first_name')
    op.add_column('sources', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sources', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sources', 'extended_title')
    # ### end Alembic commands ###
